### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by dirk99** [things4u/ESP-1ch-Gateway#10]
hi folks,
everytime when i compile i get an error with missing function checkMIC (undefined reference. I hav tryed this with VSC and arduino ide. how can i solve this?

i fond the function in _sensor but the error cames from _txRx

thanks

**Comment by platenspeler** [comment]
What is the exact message from the compiler? Did you include the lcode.h and AES include files and libraries?

btw checkMic is the right spelling..

Maarten

**Comment by platenspeler** [comment]
Hi Dirk, 

Is this issue solved? Please provide feedback on my question if not. If this issue is not followed up I need to close the issue.

Maarten

**Comment by dirk99** [comment]
Hi Maarten, yes the Problem is solved. Thanks

Am 3. Februar 2020 23:45:44 MEZ schrieb Maarten Westenberg <notifications@github.com>:
>Hi Dirk, 
>
>Is this issue solved? Please provide feedback on my question if not. If
>this issue is not followed up I need to close the issue.
>
>Maarten
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/things4u/ESP-1ch-Gateway/issues/10#issuecomment-581655628



Mit freundlichen Grüßen
Dirk Howold
Tel.  +491702309712
Mail howold@gmx.de

**Comment by platenspeler** [comment]
Thanks!
