### ISSUE TITLE
permanent setting to listen on specific channel

### ISSUE THREAD

**Issue by webgps** [things4u/ESP-1ch-Gateway#13]
Hi All,

Where can I set in the code, that the gateway listens on specific chanel instead on channel 0. I managed to set on the WEB GUI but since i have SPIFFS format 1 on every boot i have to change the channel.

Tried to set #define EU863_870 1 to 

`> #define EU863_870 2`

 no effect, the gw reports it's still listening on 868.100MHz

Tried to change the first value in freq plan  

> `{ 868100000, 125, 7, 12, 868300000, 125, 7, 12},	// Channel 0, 868.1 MHz/125 primary`

no effect neither,

Thanks in advance.

**Comment by webgps** [comment]
> Hi All,
> 
> Where can I set in the code, that the gateway listens on specific chanel instead on channel 0. I managed to set on the WEB GUI but since i have SPIFFS format 1 on every boot i have to change the channel.
> 
> Tried to set #define EU863_870 1 to
> 
> `> #define EU863_870 2`
> 
> no effect, the gw reports it's still listening on 868.100MHz
> 
> Tried to change the first value in freq plan
> 
> > `{ 868100000, 125, 7, 12, 868300000, 125, 7, 12},	// Channel 0, 868.1 MHz/125 primary`
> 
> no effect neither,
> 
> Thanks in advance.

Okay partially my fault, forget to change the first value to 868300000, now after compile an upload the gatway starts to listen on chanel 1 (868.3Mhz) by deault.
But is there any other way beyond the GUI to change this?

So it's working this way, only the GUI shows chanel 0, but this i just cosmetics
![image](https://user-images.githubusercontent.com/44380977/72327665-d4788180-36b1-11ea-9378-96593cd5ec47.png)

But I think there is a better way setting the gateway to another channel

**Comment by platenspeler** [comment]
Unfortunately, channel 0 is considered standard for gateways. If you like to have other frequency for channel 0, you have to change the .h file. 
I do not think that changing the channel in the configuration file will help much, and I plan to leave it like this.

Maarten.
