### ISSUE TITLE
Support for sim800l

### ISSUE THREAD

**Issue by note5** [things4u/ESP-1ch-Gateway#17]
Hi, thank you for this great tool, It would be great if we can be able to use a gprs/3g/4g module with this gateway

**Comment by platenspeler** [comment]
Thanks, but I do not think that I will integrate that shortly.
I put it on the wishlist!

Maarten

**Comment by note5** [comment]
Hi Maarten,
First of all I hope you are ok during this trying time. I have been trying
to see how to use a sim module like sim800l with esp or TT-GO T-call board.
This I think is interesting in making the gateway very budget friendly by
using a cheap cellar backhaul. For this to happen kindly  point out where
it needs to be tweaked as an overview?.

Best regards,
Chris
