### ISSUE TITLE
ff not defined if _STRICT_1CH = 0

### ISSUE THREAD

**Issue by strech345** [things4u/ESP-1ch-Gateway#18]
in file `_txRx.ino` this line was commented. 
`//const float ff		= root["txpk"]["freq"];			// eg 869.525`

This throw an not defined error if `_STRICT_1CH = 0`

**Comment by platenspeler** [comment]
Please verify that this issue has been resolved in the last patch update of today.

**Comment by platenspeler** [comment]
I will close this issue. I think it has been solved by the latest release. Thanks!
