### ISSUE TITLE
Setting #define OLED 0 breaks compilation

### ISSUE THREAD

**Issue by tavdog** [things4u/ESP-1ch-Gateway#23]
If I set #define OLED 0 it won't compile with following error message :
```
SP-sc-gway:305: error: 'msg_oLED' was not declared in this scope
   msg_oLED("FORMAT");
                    ^
ESP-sc-gway:367: error: 'msg_oLED' was not declared in this scope
  msg_oLED("WIFI STA");
                     ^
ESP-sc-gway:484: error: 'msg_lLED' was not declared in this scope
  msg_lLED("GET TIME",".");
                         ^
/Users/tavis/code/arduino-projects/ESP-1ch-Gateway/ESP-sc-gway/_wwwServer.ino: In lambda function:
_wwwServer:1300: error: 'msg_oLED' was not declared in this scope
   msg_oLED("FORMAT");  
```

**Comment by platenspeler** [comment]
I could have made a mistake in earlier version, but I think in any case the OLED definition is correct in the latest version. What version of Gateway are you using? It is shown iin configGway.h file.

Maarten

**Comment by tavdog** [comment]
I used V.6.2.0.E.EU868; 200129b because the Arduino app complains about the changes made for platformIO.

**Comment by platenspeler** [comment]
Ah. You can download the 6.2.3 version and copy the content of the src directory of PlatformIO to the ESP-sc-gway directory, and the content of the lib directory of PlatformIO to the libraries directory.

Maarten

**Comment by tavdog** [comment]
That works, thank you.

**Comment by platenspeler** [comment]
Good to hear, Thank you!
