### ISSUE TITLE
us-west.thethings.network not working

### ISSUE THREAD

**Issue by tavdog** [things4u/ESP-1ch-Gateway#24]
I got everything working on the eu router but when I change to  us-west.thethings.network the "Last Seen" field on the TTN console page never updates.  This might not be a problem with this firmware but I just thought I'd see if you had any ideas.  My gateway is at https://console.thethingsnetwork.org/gateways/eui-b4e62dffff85ccd1

**Comment by platenspeler** [comment]
I do not have permission to see your gateway. Could you mail me a screenshot of the GUI and indicate which line is giving you problems?

Thanks,

Maarten

BTW. For some reasons the first line of the "seen" array gets corrupted. I will have a second or third look at it :-)

**Comment by tavdog** [comment]
First image is just to show configuration of us-west.thethings.network. 
<img width="803" alt="Screen Shot 2020-02-29 at 29 Sat 11 00 02 PM" src="https://user-images.githubusercontent.com/8324295/75622712-84615b80-5b47-11ea-8c7c-f8f91ed27d9d.png">
Second image shows last seen is not getting updated.  When using route.eu it updates every 2 minutes. But with us-west it never updates.
<img width="419" alt="Screen Shot 2020-02-29 at 29 Sat 11 02 28 PM" src="https://user-images.githubusercontent.com/8324295/75622725-a0fd9380-5b47-11ea-9239-adab7dc9ff8c.png">

**Comment by platenspeler** [comment]
Please have a look at the sensors you have as well in the TTN console.
If all right, not only should the gateway be seen, but the nodes should also connect to your gateway.

In the Message History section of the GUI does it show the sensors connected to your gateway?

Sometimes the gateway does not behave alright in which case I use "FORMAT" and then "RESET" to reset the whole thing. The SPIFFS filesystem does not always behave well.

Maarten

**Comment by tavdog** [comment]
I don't have any nodes connecting at this time. I mainly wanted to setup a public gateway for my town.  I'll get a node connecting and then try us-west, maybe "last seen" is handled differently on the us-west router.  thanks for all the work on this project. Feel free to close this issue.

**Comment by platenspeler** [comment]
lastSeen is designed to only report active nodes. So if there are no nodes connected then it should not report anything. Only like I said it does report a dummy node the first time but it does report nonsense.

Maarten

**Comment by platenspeler** [comment]
So it could be that the gateway is working fine for you. Interested to hear your experiences
