### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by moibueno** [things4u/ESP-1ch-Gateway#25]
The compilation fails due to missing SECS_IN_HOUR definition.

> _utils:375:57: error: 'SECS_IN_HOUR' was not declared in this scope
> 
>      *t = (time_t)(secs - 2208988800UL + NTP_TIMEZONES * SECS_IN_HOUR);
> 

I modified the _utils file from SECS_IN_HOUR to SECS_PER_HOUR and it compiled just fine.

**Comment by platenspeler** [comment]
Please make sure that you use all the new files and not just the ones that you like. 
In the on-line version SECS_IN_HOUR is defined in configGway.h and used in _utils.ino. So you seems to make a mix between versions.

Maarten

**Comment by moibueno** [comment]
Sorry for the mistake
I will check it out
