### ISSUE TITLE
gBase64 library not compiling, pgmspace.h not found.

### ISSUE THREAD

**Issue by jpmeijers** [things4u/ESP-1ch-Gateway#3]
When trying to compile ESP-sc-gway.ino, using the recommended Base64 library, renamed to gBase64, I get the following error:
```
/home/jpmeijers/Arduino/libraries/gBase64/gBase64.cpp:2:26: fatal error: avr/pgmspace.h: No such file or directory
 #include <avr/pgmspace.h>
                          ^
```

At the top of gBase64.cpp the defines were like this:
```
#include "gBase64.h"
#include <avr/pgmspace.h>
```

And I changed it to this for the sketch to compile:
```
#include "gBase64.h"
#ifdef ESP8266
  #include <pgmspace.h>
#else
  #include <avr/pgmspace.h>
#endif
```

**Comment by platenspeler** [comment]
Yes, I removed the include I saw.
What would be the cleanest solution, as I am not maintaining base64 at all)? I can include a library directory with the dependent sources...

**Comment by jpmeijers** [comment]
Yes I think it will be nice if you include a directory with library dependencies. Then at least we know exactly which libraries and versions you use.

**Comment by platenspeler** [comment]
I’m already working on it. It will contain the gBase64 lib until I may find a way to use the standard lib.

Thanks,

Maarten
