### ISSUE TITLE
'rstTime' was not declared in this scope

### ISSUE THREAD

**Issue by jlstanus** [things4u/ESP-1ch-Gateway#30]
> /home/icity/Arduino/ESP-sc-gway/ESP-sc-gway.ino: In function 'void loop()':
> ESP-sc-gway:832: error: 'rstTime' was not declared in this scope
>    if ((nowSeconds - rstTime) >= _RST_INTERVAL) {   // Wake up every xx seconds

In Arduino 1.6.x and 1.8.x but rstTime seems to be declared at `uint32_t rstTime  = 0;		`

**Comment by bv73** [comment]
Line above, where the rstTime variable is declared, remove the backslash in the comment.
Like // last time we sent a pull_data request to server

**Comment by jlstanus** [comment]
Ok, thank you, this is fixed

**Comment by platenspeler** [comment]
Fixed in the Code. Sorry. no idea how the file got changed with \
