### ISSUE TITLE
Multiple servers not working

### ISSUE THREAD

**Issue by raymonvdm** [things4u/ESP-1ch-Gateway#4]
When i only have on server active i get the following logging

stat update: <209> {"stat":{"time":"2016-6-5 22:57:56 CET","lati":5.5579,"long":5.9145,"alti":0,"rxnb":0,"rxok":0,"rxfw":0,"ackr":0.0,"dwnb":0,"txnb":0,"pfrm":"ESP8266","mail":"admin@mail.com","desc":"ESP Gateway"}}
 Received packet of size 4 From 54.72.145.119, port 1700, Contents: 1:2D:CF:1:

But when i enable the additional server by removing the slashes here

//#define SERVER2 _MQTTSERVER             // 2nd server to send to, e.g. private server
//#define PORT2 "1700"

Then the response packet of TTN is no longer reciever / processed, and thus the gateway is not working

**Comment by platenspeler** [comment]
Raymond, this for sure is working in version 2 of the gateway. Since version 2 is a morup to dat version I recommend upgrading.
