### ISSUE TITLE
Is repeater working in the last version?

### ISSUE THREAD

**Issue by antonio-emilio** [things4u/ESP-1ch-Gateway#54]
I noticed that in the last version, the creator made some changes in the repeater mode, but I tried and didn't work....
Anyone has tried lately?

**Comment by mrpatrick1991** [comment]
Confirm it causes a crash of some kind. Error message in serial was 

Stack smashing protect failure!

abort() was called at PC 0x400ffb2b on core 1

after repeatLora:: size=24, sf=9, iiq=27, UP ch=0, DWN ch=FFFFFFFF, freq=436299776.00.

**Comment by platenspeler** [comment]
Hi,

I was working on the repeater, but I need the downlink function for that. 
When this is working, downlink should not be too much of a problem.

regards,

Maarten
