### ISSUE TITLE
it is compatible with TNN 3?

### ISSUE THREAD

**Issue by navoraul** [things4u/ESP-1ch-Gateway#85]
it is compatible with TNN V3?

**Comment by platenspeler** [comment]
For TTN version 3 please change  configGway.h and change the router setting for your ow region:

// MQTT definitions, these settings should be standard for TTN
// and need no changing. When _REPEATER function is selected, we do not
// use the backend function to send message to server over MQTT.
#if _REPEATER==0
// TTN Version 2:
//#	define _TTNSERVER "router.eu.thethings.network"
//
// TTN Version 3:
#	define _TTNSERVER "eu1.cloud.thethings.network"	
#	define _TTNPORT 1700							// Standard port for TTN
#endif
