### ISSUE TITLE
ESP-1ch-Gateway and The Thing Stack (V3) compatibility

### ISSUE THREAD

**Issue by afreisinger** [things4u/ESP-1ch-Gateway#88]
Can this gateway handle the 7-byte DevEUI parameter addressing of The Thing Stack ?

**Comment by AGudera** [comment]
There is a missmatch between TTN and the parameters to set in configNode.h.
TTN: 
Gateway ID:    eui-xxxxxxxxxxxxxxxx (from V2)
Gateway EUI: xx xx xx xx xx xx xx xx (8 byte)
API Key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

configNode.h
#  define _DEVADDR { 0x26, 0x01, 0x1B, 0x96 } 
#	define _APPSKEY { 0x02, 0x02, 0x04, 0x32, 0x00, 0x00, 0x00, 0x00, 0x54, 0x68, 0x69, 0x6E, 0x67, 0x73, 0x34, 0x55 }
#	define _NWKSKEY { 0x54, 0x68, 0x69, 0x6E, 0x67, 0x73, 0x34, 0x55, 0x54, 0x68, 0x69, 0x6E, 0x67, 0x73, 0x34, 0x55 }

However, this missmatch has to be solved.
