### ISSUE TITLE
No data shown on any app server!!!

### ISSUE THREAD

**Issue by G-3r4-d** [things4u/ESP-1ch-Gateway#96]
I have trying to use this library in TTN and Chirpstack with no success, It seems the problem is inside UDP, I;m not certain. 

Both servers let me see uplinkdata on the network server, but do not take it to the application server. Any advise to solve this issue?

**Comment by IoTThinks** [comment]
UDP packet should be at network server only.

I think app server is not dealing with UDP packet.
